apiVersion: apps/v1
kind: Deployment
metadata:
   name: order-management-deployment
   labels:
     app: order-management
spec:
  replicas: 3
  selector:
    matchLabels:
      app: order-management
  template:
    metadata:
      labels:
        app: order-management
    spec:
     containers:
     - name: order-management
       image: testImage/order-kubernetes
       ports:
         - containerPort: 9999